Repository MadKauSing/GuessFlat, pull requests merged in 2022-10, with the labels that each got.

#18 Coder kitten a5 patch 1
  helpers/change_speed.py
  helpers/helpers.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#19 added preprocessing changing pitch
  helpers/change_pitch.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#21 adding noise
  helpers/add_noise.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#23 shifiting songs
  helpers/shift_song.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#25 split files added
  helpers/split.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#26 Added Screenshot Resized and Preprocessor
  helpers/screenshot_resize_preprocess.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#28 Added Text Scanner using Tesseract
  helpers/read_text.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#29 Created using Colaboratory- Added reading the dataset and loading it
  GuessFlat.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#30 Created using Colaboratory-Added loading bars
  GuessFlat.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
